"""empty message

Revision ID: 89193f9cdf8e
Revises: 9e7a531da056
Create Date: 2023-11-28 15:19:07.149751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89193f9cdf8e'
down_revision: Union[str, None] = '9e7a531da056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
